### ISSUE TITLE
Week1

### ISSUE THREAD

**Issue by SaschaVanEssen** [khalidelkhuri/project#1]
Je processbook moet in de root directory staan als PROCESS.md. Geef daarin ook (kort) aan welke belangrijke beslissingen je hebt genomen en waarom. De diagram in je DESIGN.md is duidelijk, maar voeg nog even toe welke functies wanneer worden aangeroepen en in welke files we die terug kunnen vinden

**Comment by khalidelkhuri** [comment]
process book in root directory gezet. en DESIGN.md aangepast
